### ISSUE TITLE
Create Mail Templates and implement them in the backend

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#102]
We need some eMail templates for the mails we are going to send to the users:

- [x] eMail for confirmation of account creation. Contains an authentication code that needs to be copied.
- [x] eMail for password reset, contains the new password.
- [x] eMail for invitation to a working group.
- [x] eMail for joining request of a working group.

Use a template creator like [beefree.io](https://beefree.io/) or [stripo.email](https://stripo.email/)

**Comment by redfrexx** [comment]
Store the templates in [./WePledge/backend/src/templates/email] and make sure they are named like this: 

#### Activation email
email text:  email/activation_email.html 
email subject:  email/activation_subject.txt 
#### Password reset email 
email text: email/password_reset_email.html
email subject: email/password_reset_email_subject.txt
#### Working group invitation 
email text: email/password_reset_email.html
email subject: email/password_reset_email_subject.txt
#### Join working group request  
email text: email/password_reset_email.
email subject: email/password_reset_email_subject.txt

References: 
[Django GraphQL Auth: Email templates](https://django-graphql-auth.readthedocs.io/en/latest/settings/#email-templates)

**Comment by codingfabi** [comment]
@redfrexx Do we already have mail templates for joining requests and invitations?

**Comment by redfrexx** [comment]
yes, they already exist.
