### ISSUE TITLE
Add academic title to user registration form 

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#108]
Add academic title to user registration and/or user settings form.

**Comment by han16nah** [comment]
closed by #112

**Comment by codingfabi** [comment]
We should add the first and last name aswell...

**Comment by sami1riaz** [comment]
Added Title, first name, and last name to the registration form. Currently improving error handling for both sign-up and sign-in forms

**Comment by codingfabi** [comment]
@sami1riaz this is closed by #145 right?

**Comment by sami1riaz** [comment]
Yes!
