### ISSUE TITLE
include alex and maria in the "about us" page

### ISSUE THREAD

**Issue by sarahmadeleine** [pledge4future/WePledge#116]
images should be here https://drive.google.com/drive/u/0/folders/1NgJQHAhhOGlgEHcoACOutUCfV2X2nwGB

thanks :)

**Comment by sami1riaz** [comment]
Picking this up. (Not sure how I can assign the issue to myself)

I've requested access for the drive

**Comment by redfrexx** [comment]
@sami1riaz cool! I've sent you an invitation to the organization. Once you accept it, you should be able to assign yourself, create commits, etc

**Comment by sami1riaz** [comment]
I'm still unable to push to the project, could it be because my role is that of a member and not an owner?

Also, what should I add to Alex and Maria's descriptions?
