### ISSUE TITLE
Link imprint and privacy policy from HeiGIT

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#133]
- [x] Link Imprint button to [https://heigit.org/imprint/](https://heigit.org/imprint/)
- [x] Link Privacy policy button to [https://heigit.org/legal-notice/](https://heigit.org/imprint/)

It's a temporary solution until we have adapted the privacy policy to our app.

**Comment by sami1riaz** [comment]
Merged https://github.com/pledge4future/WePledge/pull/148 to dev-frontend
