### ISSUE TITLE
Enhance form evaluation in frontend

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#137]
Some of the forms can be evaluated in the frontend to anticipate and prevent invalid backend calls. We can do this by using the package formik. This issue collects ideas on how and which forms to evaluate:

Sign-Up Form:

- [x] Password needs to contain special character, capital letter, number etc...
- [x] eMail has to look like an email (@ sign etc.)
- [x] Both Passwords need to match 
- [x] All fields need to be filled in

**Comment by sami1riaz** [comment]
This should be dealt with as part of #108

**Comment by codingfabi** [comment]
@sami1riaz I think this is actually closed now with the formik evaluation. Feel free to reopen if you think otherwise.
