### ISSUE TITLE
Error for fetching individual heating and electricity data

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#161]
When fetching data on the individual dashboard, the queries for `heatingAggregated` and `electricityAggregated` both fail because the value `personal` for the level attribute is not valid in these queries. The error message in detail is: 

```
{
    "message": "Invalid value for parameter 'level': personal",
    "locations": [
        {
            "line": 8,
            "column": 3
        }
    ],
    "path": [
        "heatingAggregated"
    ]
}
```
I would expect the queries to work and since we do not store heating and electricity emissions on a personal level return the average of the working group that the user is in. If the user is not in a working group, I would expect the endpoint to simply return 0.

**Comment by redfrexx** [comment]
this was implemented in #241
