### ISSUE TITLE
Update co2calculator submodule

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#171]
Update co2calculator submodule to point to a certain commit in the `dev` branch.

**Comment by sami1riaz** [comment]
Have we confirmed which branch/commit we want to update the submodule to? @han16nah, @redfrexx 

Also, I haven't been able to work on this yet since I've been busy with work. Hope it's not blocking anyone

**Comment by redfrexx** [comment]
resolved in #184
