### ISSUE TITLE
Login not working on local dev setup

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#206]
When I try to log in on my local dev setup, the backend returns the following error: 

```
{
    "message": "operator does not exist: integer = uuid\nLINE 1: ...status\" WHERE \"graphql_auth_userstatus\".\"user_id\" = '0000000...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n",
    "locations": [
        {
            "line": 2,
            "column": 3
        }
    ],
    "path": [
        "tokenAuth"
    ]
}
```

The request is the standard tokenAuth mutation

**Comment by codingfabi** [comment]
After deleting and rebuilding the volumes, the old issue does not appear anmyore. However, now I get the following error when I try to sign in: 

```
django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext()
```

@redfrexx any idea on this? I looked in the repo and we do not use ugettext() anywhere^^

**Comment by redfrexx** [comment]
@codingfabi I think it should work now, at least it does on my computer.

**Comment by sami1riaz** [comment]
I guess this can be closed now?
