### ISSUE TITLE
Institutions query endpoint returns error

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#207]
When trying to call the institutions endpoint, the backend returns the following eror: 

```
Expected UUID instance, received 1\nExpected UUID instance, received 2\nExpected UUID instance, received 3...
```

I shortened the error message because it is extremely long. 
The request body looks like this: 

```
query {
        institutions {
        id
        name
        city
        country
        }
    }
```

**Comment by redfrexx** [comment]
I'm looking into it. Looks related to #206

**Comment by redfrexx** [comment]
Did you delete the docker volume containing the database? The error message sounds like the database contains integers while the data model expects uuids.

**Comment by codingfabi** [comment]
Ass you suggested, deleting and rebuilding the volumes fixed this problem :)
