### ISSUE TITLE
Choose an icon to join a working group

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#212]
We want to give the users the opportunity to request to join certain working groups. We need an icon to click on. Our possible icons are these: 

https://mui.com/material-ui/material-icons/

Leave you proposals here :)

**Comment by sarahmadeleine** [comment]
Nina and i suggest this:

import GroupsIcon from '@mui/icons-material/Groups';

**Comment by sarahmadeleine** [comment]
The icon is called Groups
