### ISSUE TITLE
Work on overview for the methodology page

### ISSUE THREAD

**Issue by sarahmadeleine** [pledge4future/WePledge#221]
- one or two sentences per section, easy access
- find icons or images, e.g. here https://mui.com/material-ui/material-icons/?query=temperature --> add it to the mockup presentation (link below)
- think about a more interesting title for the page
- clickable buttons that lead to more detailed section in the documentation
- example: https://climatetrace.org/our-approach
- our mockup: https://docs.google.com/presentation/d/16ea_L51dKWVp0d38cxOBEQvpFZ-_-GbLQuBFcA36q2k/edit#slide=id.g1b0bdae9554_0_0

**Comment by sarahmadeleine** [comment]
@codingfabi @sami1riaz we finished it - you can find the mockup here: https://docs.google.com/presentation/d/16ea_L51dKWVp0d38cxOBEQvpFZ-_-GbLQuBFcA36q2k/edit#slide=id.g1b22e6b26d6_1_0

**Comment by codingfabi** [comment]
I merged changes that should fix the display of the markdown in #223 

Closing this, reopen if still needed
