### ISSUE TITLE
Create separate user roles for users, representatives and admins

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#23]
Normal users (researchers and representatives) have too many rights still (auth, admin, etc.) which should be removed. Maybe a new user type needs to be added, e.g. [possible solution](https://stackoverflow.com/questions/34487660/django-admin-remove-permissions-from-the-list-on-add-edit-group-page)

```
class ResearcherRole(Group):
    def get_form(self, request, obj=None, **kwargs):
        # Get form from original GroupAdmin.
        form = super(ResearcherRole, self).get_form(request, obj, **kwargs)
        if 'permissions' in form.base_fields:
            permissions = form.base_fields['permissions']
            permissions.queryset = permissions.queryset.exclude(content_type__app_label__in=['admin', 'auth']) # Example
        return form
```

**Comment by codingfabi** [comment]
Adding this to the working group project because roles are really just required there
