### ISSUE TITLE
Add endpoint to remove users from a working group

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#246]
We should provide the representatives of working groups with the possibility to remove users from a working group. The backend should provide a mutation endpoint that takes a user id as an argument and removes it from the working group. 

Open Questions: 

- [ ] What happens to past emission entries entered by the user? I would suggest they stay and still contribute to the working groups total emissions.

Endpoint Exceptions to raise: 

- [ ] Return a 404 error if the user_id was not found in the working group.

**Comment by redfrexx** [comment]
related to #265
