### ISSUE TITLE
Cleanup different research_fields fixtures

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#252]
We have two `research_fields.json` files, which I think is unnecessarry.

![Screenshot 2023-02-18 at 18 13 32](https://user-images.githubusercontent.com/17953957/219879111-890e3ba9-5d43-4547-8066-4d3fa711ba3b.png)

@redfrexx  can we delete one or are these different files?

**Comment by redfrexx** [comment]
yes the one in the `./emissions/data` folder can be deleted
