### ISSUE TITLE
BusinessTrip Entries are not created

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#259]
When creating a business trip emission entry, the entry also needs to be assigned to the working group of the creating user. This works similarly for commuting, but not for business trips. 

Observation: 

The creation function of commuting has the following code snippet: 

```
commuting_group_instance = CommutingGroup(
                working_group=user.working_group,
                timestamp=str(d),
                transportation_mode=input.transportation_mode,
                n_employees=user.working_group.n_employees,
                co2e=group_data["co2e"],
                co2e_cap=co2e_cap,
                distance=group_data["distance"],
            )

commuting_group_instance.save()
```

This is missing in the creation of the business trips. We should probably add similar code to the `CreateBusinessTrip` function.

**Comment by codingfabi** [comment]
However, I am a bit confused. We have the following situation: 

We have a `BusinessTrip` entity that has a userID and a working_groupID as foreign keys. Furthermore, we have a `BusinessTripGroup`entity that has just a working_groupID as a foreign key. During creation, we only create the `BusinessTrip`Entity. 

In the `resolve_total_emission` function, we resolve the BusinessTrips from the `BusinessTripGroup` entities: 

```
businesstrips_emissions = (
            BusinessTripGroup.objects.filter(timestamp__gte=start, timestamp__lte=end)
            .values(*aggregate_on)
            .annotate(**metrics)
        )
businesstrips_df = pd.DataFrame(list(businesstrips_emissions))  
```

However, this is always empty because we never save objects into the `BusinessTripGroup` table.

@redfrexx What are your thoughts on how we should resolve this? Should we: 

1. Save extra business trip entires into the `BusinessTripGroup` table
2. Resolve Group and Institution business trips from the `BusinessTrip` table

**Comment by redfrexx** [comment]
The `BusinessTrip` table contains all the single business trips provided by the users. `BusinessTripGroup` contains the monthly aggregated co2 emissions based on the `BusinessTrip` table. Once a new business trip is created by the user, the respective row in the `BusinessTripGroup` table should be updated. This is done in the [`Businesstrip.save()` method](https://github.com/pledge4future/WePledge/blob/1fc6c1d694f7f2d25f9cc1d268ca0f1e3d905299/backend/src/emissions/models/businessTrip.py#L54-L93). There might be a bug in it though if the `BusinessTripGroup` table remains empty. Also there is issue #54 which is related to updating `BusinessTripGroup` when a `BusinessTrip` entry is deleted. I can a take a look at it this week or do you want to, @codingfabi ?

**Comment by codingfabi** [comment]
Okay, did not know about the `businesstrip.save()` function. I will have a look at it and we can talk about it on thursday :)

**Comment by codingfabi** [comment]
As it turns out, the save function is not at all broken and I am just stupid. I created the BusinessTrip entries before adding the creating user to the working group... makes sense that they are not part of the BusinessTripGroup table then. 

However, the creation of BusinessTrips is broken nonetheless because of these lines in the BusinessTrip saving function: 

```
year = self.timestamp[:4]#.year
month = self.timestamp[5:7]#.month
```

I am changing the title of the issue and will fix this in a PR.
