### ISSUE TITLE
Compile a list of research fields for `WorkingGroup.research_field`

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#28]
`WorkingGroup` model contains a field `research_field` so we can later calculate the average co2e emissions per research field. For this we need to define a list of valid research fields which the representative user of a working groups chooses from.

**Comment by redfrexx** [comment]
We will use the EU Classification: 
- https://joinup.ec.europa.eu/collection/eu-semantic-interoperability-catalogue/solution/field-science-and-technology-classification/about
- https://www.oecd.org/science/inno/38235147.pdf

Needs to be digitized though. Try to follow this structure and save it as a .json file

``` json
{ "natural sciences": 
   ["Mathematics", 
    "Computer and information science", ...],
   "Engineering and Technology": [...]
   "Agricultural Sciences": [...]}
```

**Comment by nkrasovec** [comment]
[research_fields.zip](https://github.com/pledge4future/WePledge/files/7684798/research_fields.zip)
