### ISSUE TITLE
Link in registration confirmation email does not work

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#285]
The link in the registration confirmation email which should lead back to the webpage does not work.

**Comment by redfrexx** [comment]
Same for the link in the join working group request email.

**Comment by codingfabi** [comment]
This is probably a backend task right? I would assume we have to adjust the mail templates.

Here is what we need to fix: 

- [ ] Link in the confirm email leads to pledge4future.com/activte -> change to pledge4future.com/confirm-email
- [ ] Working Group Join Request does not have a link -> change to pledge4future.com/working-group-details
