### ISSUE TITLE
Remove line connecting bars in emissions figure

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#287]
The line connecting the bars in the emissions figure has a bug. When disabling one category, the line is still drawn as if the category was still on. (See below) But actually it does not need to be fixed, but the line can be removed, since it is not really necessary.

<img width="1081" alt="Screenshot 2023-05-23 at 21 20 26" src="https://github.com/pledge4future/WePledge/assets/5021557/1c70f087-15e2-4a8c-8c6c-9f1f28e37ac9">

**Comment by codingfabi** [comment]
Closes this because it is already mentioned in #289 

Feel free to reopen if I am missing something and this is needed nonetheless :)
