### ISSUE TITLE
Demo plot

### ISSUE THREAD

**Issue by sarahmadeleine** [pledge4future/WePledge#299]
- Electricity, heating… buttons at the bottom should be in one line (Firefox browser)
- Label “November” is missing (Firefox browser)
- There is not enough space between some bar labels (e.g. August, September) (Firefox browser)
- Add some values for group and institute emissions
- Y axis overlaps with y axis label

**Comment by codingfabi** [comment]
Technical steps:

- [ ] Check responsive grid layout for plot buttons
- [ ] Check why firefox behaves differently than chrome.
- [ ] Fix Y-Axis label (probably have to make container larger)


@sarahmadeleine Which firefox version are you using? 

Also, there should be values for group and institute emissions in the demo. At least for me, can you maybe check this one more time?

**Comment by sarahmadeleine** [comment]
@codingfabi it's Mozilla Firefox 113.0.2

**Comment by codingfabi** [comment]
I can repdroduce broken Group and Institute Emissions in dem demo dashboard now. Adding Prio:High label because this should be fixed ASAP.
