### ISSUE TITLE
Privacy policy for website

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#43]
Check https://datenschutz-generator.de/impressum/

**Comment by redfrexx** [comment]
Open questions for privacy policy: 

1. Setzen Sie Cookies ein (bzw. binden Tools oder Inhalte in Ihr Onlineangebot ein, die Cookie einsetzen)?

Bitte wählen Sie, falls eingesetzt, die von Ihnen verwendeten Cookie-Management-Lösung aus:
BorlabsCookie

- ccm19
- consentmanager / Händlerbund
- Conversant Consent Tool
- Cookiebot
- Cookiefirst
- Klaro!
- Iubenda
- OneTrust
- Quantcast
- Sourcepoint
- TrustArc
- Usercentrics

**Comment by redfrexx** [comment]
Wird Ihr Onlineangebot von einem fremden Server abgerufen (z.B. bei einem Webhostinganbieter, bzw. Homepage-Baukasten)?

Bitte wählen Sie, sofern zutreffend, welche Verfahren und Funktionen Sie nutzen:
- Webhosting umfasst E-Mail-Versand und -Hosting
- Es werden Zugriffsdaten und Logfiles verarbeitet
- Einsatz eines Content-Delivery-Networks 

Wird Ihr Onlineangebot bei einem sog. Homepage-Baukasten-Anbieter gehostet?
- IONOS by 1&1
- GoDaddy
- Homepage-Baukasten.de
- Jimdo
- SquareSpace
- Webflow
- web4business
- Webnode
- Weebly
- Wix
- WordPress.com

**Comment by redfrexx** [comment]
Soll die Datenschutzerklärung (auch) für eine mobile oder Web-Applikation gelten? - ja 

Trifft eines der folgende Dinge zu: 

- Speicherung des universellen und eindeutigen Identifikators (UUID)
- Speicherung eines (anderen) pseudonymen Identifikators 
- Geräteberechtigungen für den Zugriff auf Funktionen und Daten …

**Comment by redfrexx** [comment]
Community Funktionen #71

**Comment by redfrexx** [comment]
Nutzen Sie über das Internet zugängliche Cloud-Dienste, wie z.B. Google Suite oder Micosoft OneDrive?

For now, yes (collect emails through google forms)

**Comment by redfrexx** [comment]
Versenden Sie einen Newsletter oder vergleichbare Arten von elektronischen Nachrichten?

Not now, but maybe in the future? 

- Erfolgsmessung (Messung von Öffnungsraten und Klickraten)
- Newsletter-Tracking mit Google Analytics
- Newsletter als Voraussetzung für Gratis-Leistungen
- Versand (auch) via SMS 

Falls Sie einen Versanddienstleister einsetzen, wählen Sie ihn bitte aus: 

Selection see in the tool

**Comment by redfrexx** [comment]
Setzen Sie Dienste und Verfahren zur Webanalyse, A/B - Testing und Optimierung ein?

Bitte wählen Sie einen der verwendeten Anbieter oder der Verfahren aus (bitte lesen Sie zudem die Erläuterungen):

z.Bps. 
-  1&1 WebAnalytics
- AB Tasty
- Adobe Analytics
- Amazon Personalize
- Bugsnag

**Comment by redfrexx** [comment]
Setzen Sie Dienste und Verfahren zu Zwecken des Onlinemarketings ein (z.B. Google Analytics oder das Facebook-Pixel)? z.Bsp.

- Google Tag Manager
- Google Analytics
- Zielgruppenbildung mit Remarketing-, bzw. Analytics-Audiences
- Aktiviertes Universal Analytics

**Comment by redfrexx** [comment]
Binden Sie fremde Inhalte, wie z.B. Social, Plugins, Youtube-Videos, Schriftarten, etc. in Ihr Onlineangebot ein?


Setzen Sie Dienstleistungen, Plattformen und Software anderer Anbieter zu Zwecken der Organisation, Verwaltung, Planung oder sonst als Hilfswerkzeuge ein?

**Comment by codingfabi** [comment]
1. Cookies: bisher noch keine, kommt dann voraussichtlich erst wenn wir login und nutzerverwaltung anbieten. 
2. Webhosting Anbieter: Da wo wir unseren Server gemietet haben. Da einfach mal alle 3 ankreuzen. Baukastenanbieter nutzen wir nicht. 
3:
- Speicherung des universellen und eindeutigen Identifikators (UUID) -> nein (zumindest so far nicht)
- Speicherung eines (anderen) pseudonymen Identifikators -> nein
- Geräteberechtigungen für den Zugriff auf Funktionen und Daten … -> nein
4:
Nutzen Sie über das Internet zugängliche Cloud-Dienste, wie z.B. Google Suite oder Micosoft OneDrive? -> nein 
5:
Versenden Sie einen Newsletter oder vergleichbare Arten von elektronischen Nachrichten? -> Ja, die subscription für die eMail Liste über google docs.
6:
Setzen Sie Dienste und Verfahren zur Webanalyse, A/B - Testing und Optimierung ein? -> Nein
7:
Setzen Sie Dienste und Verfahren zu Zwecken des Onlinemarketings ein (z.B. Google Analytics oder das Facebook-Pixel)? -> Ja, Matomo
8: 
Binden Sie fremde Inhalte, wie z.B. Social, Plugins, Youtube-Videos, Schriftarten, etc. in Ihr Onlineangebot ein? -> Nein

Setzen Sie Dienstleistungen, Plattformen und Software anderer Anbieter zu Zwecken der Organisation, Verwaltung, Planung oder sonst als Hilfswerkzeuge ein? -> Weiß nicht, GitHub vielleicht. Sollten wir vorsichtshalber mal mit ja beantworten.
