### ISSUE TITLE
Improve authentication security in frontend and backend

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#57]
So far, the login functionality only checks for a token cookie, regardless of its value. 
We need to develop a proper check on the validity of the token. 
ToDo:

- [x] provide graphql endpoint to check validity of token, should return user ("Me-Query")
- [x] use this endpointin frontend and always check logged in status
- [x] implement global user singleton to store information of logged in user

**Comment by redfrexx** [comment]
I found a  bug in the authentication settings and fixed it. Maybe the issue with checking the validity of the token is solved by this as well. At least the `me-query' works now using the following test:

https://github.com/pledge4future/WePledge/blob/ef6efa6208e07f1e2a199f1938b74b4b35e2da30/backend/src/emissions/tests.py#L122-L137

I've also added some [more unit tests](https://github.com/pledge4future/WePledge/blob/dev-backend-auth/backend/src/emissions/tests.py) to check whether the API queries for user authentication work properly. Some are still missing though.

**Comment by redfrexx** [comment]
I will also look into how to make sure that the API requests only return results if the user is authenticated, i.e a valid token is provided in header.

**Comment by codingfabi** [comment]
Should have been closed with #56
