### ISSUE TITLE
License and Repo Presentation

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#59]
Since we are going to publish the repository and go OpenSource, we should rework some of the repository presentation and think about a license as well. Therefor we have to 

- [x] adjust the readmes of all branches. Avoid the sensitive data that is written is some of thes readmes. (e.g. admin password in the readme of the dev branch). This does not require coding experience. Check all the readme files in all the branches, remove sensitive information and store them somewhere else (e.g. Google Drive) and add a descriptive text when needed. It is important that we avoid information leak.
- [x] do some research on what software license is most suitable for OpenSource projects like ours. There should be good tutorials online on how to choose a proper license.

**Comment by veitu** [comment]
I removed the django login information from all readmes and saved them in bitwarden

**Comment by veitu** [comment]
Main question regarding license: Should people be allowed to make closed source versions from our code or not?
In the first case, we could use a permissive license like the MIT license. In the second case, we could use a copyleft license like the GPL v3 license. I think the GPL v3 license is better.

The GLP v3 license still allows commercial use but it requires people to make their code publicly availabe and indicate any changes they made to the original code.

more info about the GPL v3 license: https://www.gnu.org/licenses/quick-guide-gplv3.en.html

**Comment by veitu** [comment]
license has been added in dev-backend branch
