### ISSUE TITLE
Address in impressum is not shown

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#67]
The address is missing on the [impressum page](https://pledge4future.org/impressum). It probably happened after I've replaced the [address.png](https://github.com/pledge4future/WePledge/blob/demo/frontend/public/static/images/address.png) in commit 8e1795c.

**Comment by codingfabi** [comment]
The adress should be visible now. @redfrexx pls check whether this is the correct one and close the issue if it is the case.
