### ISSUE TITLE
Backend refuses frontend calls because of CORS regulatory

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#93]
The backend does currently not allow requests from different origins (see response to a login attempt from localhost:3000 in the screenshot)

![grafik](https://user-images.githubusercontent.com/17953957/150637602-840999ef-68c0-4997-83b8-6cacd8d1eb99.png)

We should configure an exception for CORS requests from localhost:3000 in the backend

**Comment by redfrexx** [comment]
I've added an exception for CORS requests. Hope this solves the issue.  

https://github.com/pledge4future/WePledge/blob/3ae9c2b4f54e4f70feccd61e8331d0069bacfbf7/backend/src/pledge4future/settings.py#L35-L39
